services:
  printmqttify:
    image: printmqttify
    container_name: printmqttify_container
    privileged: true
    ports:
      - "1631:631"
      - "8080:8080"
    devices:
      - "/dev/bus/usb/001/004:/dev/bus/usb/001/004"
    environment:
      - MQTT_BROKER=192.168.1.175
      - MQTT_USERNAME=mqtt-username
      - MQTT_PASSWORD=password
      - MQTT_TOPIC=printer/commands
      - ADMIN_USER=admin
      - ADMIN_PASS=adminpassword
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    stdin_open: true
    tty: true
