# Listen on all network interfaces on port 631
#Port 631
Listen 0.0.0.0:631
# Listen [::]:631 #only required for ipv6
Listen /var/run/cups/cups.sock

# Default log levels
LogLevel warn

# Allow remote access to the server
<Location />
  Order allow,deny
  Allow all
</Location>

# Allow remote access to the admin pages
<Location /admin>
  Order allow,deny
  Allow all
</Location>

# Allow access to configuration files
<Location /admin/conf>
  AuthType Default
  Require user @SYSTEM
  Order allow,deny
  Allow all
</Location>

# Share printers on the local network
Browsing On
BrowseLocalProtocols dnssd

# Enable printer sharing and remote administration
DefaultAuthType Basic
WebInterface Yes

# Kill a stalled job after 5 minutes instead of the 3h default
MaxJobTime 300

# Drop a failed job instead of disabling the whole queue
ErrorPolicy abort-job
